language: cpp

before_install:
  - yes | sudo add-apt-repository ppa:zoogie/sdl2-snapshots
  - yes | sudo add-apt-repository ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev gcc-4.8 cpp-4.8

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make

notifications:
  email: false